import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '@/styles/globals.css'
import {SessionProvider} from "next-auth/react";
import Layout from "@/Components/Layout/Layout";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <SessionProvider>
      <Layout>
        {children}
      </Layout>
     </SessionProvider>
    </body>
    </html>
  )
}
